require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WatchesController do

  # This should return the minimal set of attributes required to create a valid
  # Watch. As you add validations to Watch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WatchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all watches as @watches" do
      watch = Watch.create! valid_attributes
      get :index, {}, valid_session
      assigns(:watches).should eq([watch])
    end
  end

  describe "GET show" do
    it "assigns the requested watch as @watch" do
      watch = Watch.create! valid_attributes
      get :show, {:id => watch.to_param}, valid_session
      assigns(:watch).should eq(watch)
    end
  end

  describe "GET new" do
    it "assigns a new watch as @watch" do
      get :new, {}, valid_session
      assigns(:watch).should be_a_new(Watch)
    end
  end

  describe "GET edit" do
    it "assigns the requested watch as @watch" do
      watch = Watch.create! valid_attributes
      get :edit, {:id => watch.to_param}, valid_session
      assigns(:watch).should eq(watch)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Watch" do
        expect {
          post :create, {:watch => valid_attributes}, valid_session
        }.to change(Watch, :count).by(1)
      end

      it "assigns a newly created watch as @watch" do
        post :create, {:watch => valid_attributes}, valid_session
        assigns(:watch).should be_a(Watch)
        assigns(:watch).should be_persisted
      end

      it "redirects to the created watch" do
        post :create, {:watch => valid_attributes}, valid_session
        response.should redirect_to(Watch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved watch as @watch" do
        # Trigger the behavior that occurs when invalid params are submitted
        Watch.any_instance.stub(:save).and_return(false)
        post :create, {:watch => { "name" => "invalid value" }}, valid_session
        assigns(:watch).should be_a_new(Watch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Watch.any_instance.stub(:save).and_return(false)
        post :create, {:watch => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested watch" do
        watch = Watch.create! valid_attributes
        # Assuming there are no other watches in the database, this
        # specifies that the Watch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Watch.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => watch.to_param, :watch => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested watch as @watch" do
        watch = Watch.create! valid_attributes
        put :update, {:id => watch.to_param, :watch => valid_attributes}, valid_session
        assigns(:watch).should eq(watch)
      end

      it "redirects to the watch" do
        watch = Watch.create! valid_attributes
        put :update, {:id => watch.to_param, :watch => valid_attributes}, valid_session
        response.should redirect_to(watch)
      end
    end

    describe "with invalid params" do
      it "assigns the watch as @watch" do
        watch = Watch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Watch.any_instance.stub(:save).and_return(false)
        put :update, {:id => watch.to_param, :watch => { "name" => "invalid value" }}, valid_session
        assigns(:watch).should eq(watch)
      end

      it "re-renders the 'edit' template" do
        watch = Watch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Watch.any_instance.stub(:save).and_return(false)
        put :update, {:id => watch.to_param, :watch => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested watch" do
      watch = Watch.create! valid_attributes
      expect {
        delete :destroy, {:id => watch.to_param}, valid_session
      }.to change(Watch, :count).by(-1)
    end

    it "redirects to the watches list" do
      watch = Watch.create! valid_attributes
      delete :destroy, {:id => watch.to_param}, valid_session
      response.should redirect_to(watches_url)
    end
  end

end
